export const characters = [
    "a treacherous merchant",
    "a loyal sidekick",
    "a cunning sorcerer",
    "a fierce warrior",
    "a stealthy rogue",
    "a noble knight",
    "a mysterious bard",
    "a vengeful spirit",
    "a disgraced noble",
    "a forgotten god",
    "a curious scholar",
    "a resourceful ranger",
    "a ruthless warlord",
    "a benevolent healer",
    "a renegade pirate",
    "a haunted paladin",
    "a mystical druid",
    "a charming swindler",
    "a fierce barbarian",
    "an enigmatic oracle",
    "a rebellious prince/princess",
    "a cursed blacksmith",
    "an exiled monarch",
    "a zealous cleric",
    "a devious assassin",
    "a wandering nomad",
    "a corrupted priest",
    "a holy knight",
    "a reclusive alchemist",
    "a determined hunter",
    "a playful trickster",
    "a brave adventurer",
    "a sinister necromancer",
    "a devoted monk",
    "a lost child",
    "an enchanted beast",
    "a fearless captain",
    "a time-traveling mage",
    "an ancient dragon",
    "a skilled artisan",
    "a tragic hero",
    "a wisecracking thief",
    "a silent guardian",
    "a cursed noble",
    "a daring explorer",
    "a forgotten hero",
    "a blind prophet",
    "a brave soldier",
    "a calculating tactician",
    "a wandering minstrel",
    "a fallen angel",
    "a stoic blacksmith",
    "a feral werewolf",
    "a gentle giant",
    "a paranoid scholar",
    "a jovial innkeeper",
    "a mischievous fae",
    "a ghostly apparition",
    "a heroic outlaw",
    "a loyal retainer",
    "a ruthless bounty hunter",
    "a patient gardener",
    "a wise hermit",
    "a cunning shapeshifter",
    "a vigilant watchman",
    "a conflicted spy",
    "a ghostly knight",
    "a shrewd politician",
    "a vengeful widow",
    "a daring smuggler",
    "a noble philanthropist",
    "a cursed artist",
    "a reformed villain",
    "a brave sailor",
    "an eccentric inventor",
    "a lost explorer",
    "a fierce gladiator",
    "a pacifist healer",
    "a corrupt judge",
    "a jovial bard",
    "a hardened mercenary",
    "a benevolent spirit",
    "a secretive librarian",
    "a wild druid",
    "a tortured artist",
    "a brave diplomat",
    "a fallen hero",
    "a loyal squire",
    "a shadowy figure",
    "a mysterious benefactor",
    "a determined farmer",
    "a noble defender",
    "a curious child",
    "a wise elder",
    "a fearless leader",
    "a jovial merchant",
    "a shamanistic healer",
    "a royal guard"
];

export const goals = [
    "retrieve a lost artifact",
    "rescue a captured ally",
    "uncover an ancient secret",
    "defend a village from raiders",
    "escort a caravan safely",
    "assassinate a tyrant",
    "solve a series of murders",
    "steal a powerful relic",
    "sent to negotiate peace between factions",
    "find a cure for a deadly disease",
    "sabotage an enemy stronghold",
    "charged to protect a sacred site",
    "explore a haunted mansion",
    "recover stolen plans",
    "ordered to infiltrate a cult",
    "escort a VIP through dangerous territory",
    "defend a fort under siege",
    "find a missing scout",
    "capture a notorious bandit",
    "decipher an ancient prophecy",
    "assigned to build an outpost",
    "gather intel on enemy movements",
    "retrieve a magical ingredient",
    "estigate strange occurrences",
    "escort a diplomat to a summit",
    "defeat a rampaging beast",
    "clear a dungeon",
    "rescue prisoners of war",
    "retrieve a lost heirloom",
    "sent to stop a ritual",
    "find a way to stop a plague",
    "sabotage a magical portal",
    "charged to protect a royal family",
    "deliver a critical message",
    "rescue a kidnapped noble",
    "recover a legendary weapon",
    "iltrate an enemy camp",
    "protect a merchant caravan",
    "ordered to capture a rogue mage",
    "retrieve a forbidden tome",
    " gather rare herbs",
    "assigned to find a hidden treasure",
    "defend a border town",
    "stop a smuggling ring",
    "estigate a lost expedition",
    "escort refugees to safety",
    "find a hidden sanctuary",
    "guard a shipment of gold",
    "capture a runaway criminal",
    "sabotage a siege engine",
    "sent to investigate an abandoned mine",
    "protect a sacred relic",
    "uncover a spy network",
    "charged to defend a wizard’s tower",
    "find and close a demon portal",
    "deliver supplies to a besieged city",
    "find an ancient map",
    "rescue survivors from a disaster",
    "iltrate a masquerade ball",
    "track down a rare beast",
    "gather evidence of corruption",
    "free a wrongly accused prisoner",
    "sent to negotiate a ransom",
    "protect a valuable artifact",
    "escort a healer to a plague site",
    "recover a stolen spellbook",
    "stop an assassination plot",
    "estigate a cursed village",
    "ordered to explore an uncharted island",
    "defend a temple from invaders",
    "find a missing diplomat",
    "sabotage a mining operation",
    "protect a group of pilgrims",
    "retrieve a magical crystal",
    "charged to defeat a rival guild",
    "stop a warlord’s plans",
    "protect a library of ancient texts",
    "uncover a hidden conspiracy",
    "find the source of dark magic",
    "rescue a stranded expedition",
    "sent to destroy a dangerous artifact",
    "capture a rebel leader",
    "guard a sacred grove",
    "recover an ancient artifact",
    "defeat a powerful demon",
    "protect a trade route",
    "retrieve a lost manuscript",
    "estigate a series of disappearances",
    "sabotage a fleet of ships",
    "charged to rescue a besieged garrison",
    "escort a bard to a royal court",
    "find a cure for a magical illness",
    "protect a village from a curse",
    "stop a dangerous cult ritual",
    "rescue a child from kidnappers",
    "sent to uncover a hidden temple",
    "defend a fortress from attackers",
    "retrieve a stolen banner",
    "gather rare ingredients",
    "uncover the truth behind a legend",
    "protect a scholar on a quest",
    "find a mythical creature"
];

export const locations = [
    "an abandoned castle",
    "a bustling underground market",
    "a mysterious forest",
    "a haunted mansion",
    "a desolate island",
    "an ancient ruin",
    "a sacred temple",
    "a remote mountain village",
    "a forgotten city",
    "a magical grove",
    "a stormy sea",
    "a war-torn battlefield",
    "a secret laboratory",
    "a dragon’s lair",
    "a sunken ship",
    "a royal palace",
    "a cursed swamp",
    "an enchanted garden",
    "a floating island",
    "a shadowy forest",
    "a maze-like cavern",
    "a ghost town",
    "a wizard's tower",
    "a desolate desert",
    "an icy tundra",
    "a hidden valley",
    "a labyrinthine dungeon",
    "a mystical monastery",
    "a celestial plane",
    "an underground cavern",
    "a forgotten fortress",
    "a bustling port city",
    "a high cliffside",
    "a serene oasis",
    "a lava-filled chasm",
    "a plague-ridden town",
    "a treacherous mountain path",
    "an ancient library",
    "a secret guild hall",
    "a magical battlefield",
    "a fog-shrouded moor",
    "a haunted graveyard",
    "a dark forest",
    "a hidden underwater city",
    "a sacred pilgrimage trail",
    "a nomadic caravan camp",
    "a feywild grove",
    "a bustling metropolis",
    "a mystical ley line",
    "a clockwork city",
    "a star-lit observatory",
    "an elemental plane",
    "a forgotten mine",
    "druidic circle",
    "a bandit camp",
    "a legendary battlefield",
    "a subterranean labyrinth",
    "a royal crypt",
    "a verdant plateau",
    "a sorcerer's sanctum",
    "a seedy tavern",
    "a wizard's college",
    "a foggy coastline",
    "a hunter’s lodge",
    "a tranquil monastery",
    "a desolate wasteland",
    "a celestial island",
    "an ancient coliseum",
    "a pirate's cove",
    "a moonlit grove",
    "a cursed battlefield",
    "a reclusive monastery",
    "an ancient arena",
    "a darkened alley",
    "a holy pilgrimage site",
    "a desolate ice cave",
    "a thriving marketplace",
    "a secluded hermitage",
    "a distant star",
    "a gnomish workshop",
    "a haunted asylum",
    "a mystical forge",
    "a sun-scorched plateau",
    "a serene village",
    "a spectral realm",
    "a cryptic maze",
    "a sacred mountaintop",
    "an ancient grove",
    "a bustling bazaar",
    "a forgotten realm",
    "a dragon’s hoard",
    "a haunted lighthouse",
    "a hidden sanctuary",
    "a demon-infested ruin",
    "a tranquil lake",
    "a mystical forest clearing",
    "a bustling trade post",
    "a windswept canyon",
    "an ancient battlefield",
    "a serene mountain retreat",
    "a dragon’s nest",
    "a hidden monastery",
    "a celestial observatory",
    "an otherworldly dimension"
];

export const obstacles = [
    "guarded by undead warriors",
    "trapped with deadly puzzles",
    "hunted by rival adventurers",
    "protected by a powerful curse",
    "defended by enchanted traps",
    "blocked by a magical barrier",
    "ested with deadly creatures",
    "hidden in a maze of tunnels",
    "patrolled by a vigilant guard",
    "sealed by ancient magic",
    "guarded by a fearsome dragon",
    "surrounded by treacherous terrain",
    "booby-trapped with explosive runes",
    "guarded by a group of mercenaries",
    "hidden within shifting sands",
    "defended by an army of golems",
    "protected by a horde of minions",
    "guarded by a fierce warlord",
    "obscured by illusionary magic",
    "ested with giant spiders",
    "hidden behind a waterfall",
    "guarded by spectral knights",
    "defended by a powerful sorcerer",
    "hidden in a labyrinthine dungeon",
    "protected by elemental guardians",
    "trapped in a time loop",
    "guarded by a monstrous beast",
    "hidden within a dense forest",
    "protected by a ring of fire",
    "guarded by a tribe of barbarians",
    "defended by an elite squad",
    "blocked by a fallen bridge",
    "guarded by a mythical creature",
    "surrounded by a magical storm",
    "trapped in a sinking ship",
    "guarded by a haunted spirit",
    "hidden in an icy cavern",
    "protected by a shield of light",
    "guarded by a stone colossus",
    "trapped in an enchanted mirror",
    "defended by a dark wizard",
    "surrounded by a toxic swamp",
    "guarded by shadowy figures",
    "hidden within a volcano",
    "protected by a barrier of thorns",
    "guarded by a powerful lich",
    "trapped in a cursed painting",
    "defended by a swarm of bats",
    "blocked by a raging river",
    "guarded by a clan of ninjas",
    "surrounded by enchanted fog",
    "hidden in a forgotten temple",
    "protected by a circle of stones",
    "guarded by a demonic entity",
    "trapped in a sinking bog",
    "defended by a fire-breathing dragon",
    "guarded by a cursed knight",
    "hidden in a field of illusions",
    "protected by a forcefield",
    "guarded by a band of pirates",
    "surrounded by enchanted vines",
    "blocked by a rockslide",
    "guarded by a pack of wolves",
    "trapped in a shifting maze",
    "protected by a wall of ice",
    "guarded by a vengeful spirit",
    "hidden within a mountain pass",
    "protected by a magical fog",
    "guarded by a thunderous beast",
    "trapped in a collapsing cave",
    "defended by a clan of warriors",
    "guarded by a cursed relic",
    "hidden in a forest of shadows",
    "protected by a blizzard",
    "guarded by a swamp monster",
    "trapped in an abandoned mine",
    "defended by a sentient tree",
    "surrounded by a sandstorm",
    "hidden in a sunken ruin",
    "guarded by a basilisk",
    "protected by a spell of confusion",
    "trapped in a haunted crypt",
    "guarded by a werewolf pack",
    "blocked by a landslide",
    "protected by an ancient seal",
    "guarded by an iron golem",
    "hidden in a snowy tundra",
    "surrounded by a moat of lava",
    "protected by a magical mist",
    "guarded by a cursed artifact",
    "trapped in a phantom ship",
    "defended by a frost giant",
    "guarded by a lightning storm",
    "protected by a ring of ice",
    "hidden in a desert oasis",
    "surrounded by enchanted flames",
    "guarded by a feral beast",
    "trapped in a deadly game",
    "defended by an ethereal guardian"
];

export const twists = [
    "allies turn into enemies",
    "a powerful storm disrupts plans",
    "a long-lost mentor reappears",
    "a traitor in the group",
    "magic stops working",
    "time flows differently",
    "a hidden agenda is revealed",
    "a rival claims the prize",
    "everything is an illusion",
    "a mysterious benefactor aids the party",
    "a sudden betrayal",
    "the enemy seeks redemption",
    "a curse affects everyone",
    "a hidden passage is found",
    "a forgotten ally returning",
    "memories are altered",
    "reality is distorted",
    "a natural disaster strikes",
    "an ancient prophecy fulfilled",
    "technology fails",
    "dreams become reality",
    "a secret society intervenes",
    "a race against time",
    "the dead rise again",
    "shadows come to life",
    "a powerful artifact awakens",
    "a sudden invasion",
    "the weather turns deadly",
    "illusions conceal truths",
    "an ally is possessed",
    "a double-cross is revealed",
    "all seems lost",
    "visions predict doom",
    "a mysterious illness spreads",
    "trust is broken",
    "the ground shifts",
    "a powerful entity awakens",
    "unexpected reinforcements",
    "the past haunts the present",
    "secrets are uncovered",
    "a dire prophecy revealed",
    "an old enemy returns",
    "a hidden portal is found",
    "a powerful curse lifted",
    "a key item is lost",
    "a deadly trap is sprung",
    "allies are mind-controlled",
    "a race against an eclipse",
    "the truth is stranger",
    "a hidden enemy lurks",
    "a sudden change of heart",
    "the leader is captured",
    "ancient technology revives",
    "an unexpected alliance begins",
    "reality fractures",
    "a powerful spell backfires",
    "nature goes berserk",
    "an enemy seeks peace",
    "everyone forgets",
    "a doppelganger is found",
    "time loops endlessly",
    "a sudden moral dilemma",
    "a secret is unveiled",
    "a forbidden area opens",
    "a desperate gamble",
    "the heroes are framed",
    "the sun never sets",
    "a powerful weapon is used",
    "an unexpected death",
    "an ally is a spy",
    "an ancient evil awakens",
    "all magic is drained",
    "a lost civilization discovered",
    "the moon shatters",
    "the sea becomes hostile",
    "gravity shifts",
    "a sudden epidemic",
    "the heroes turn against each other",
    "the stars align",
    "day and night swap",
    "a hidden map is found",
    "the ground opens",
    "dreams invade reality",
    "a deal is struck",
    "an artifact causes chaos",
    "a prophecy is false",
    "an unexpected hero rises",
    "emotions are manipulated",
    "a secret is revealed",
    "heroes are cursed",
    "an alternate dimension overlaps",
    "the sky darkens",
    "a powerful entity is bound",
    "a hero disappears",
    "a shadows speak",
    "silence falls",
    "an unbreakable oath",
    "the heroes face their fears"
];
