export const characters = [
    "a treacherous merchant",
    "a loyal sidekick",
    "a cunning sorcerer",
    "a fierce warrior",
    "a stealthy rogue",
    "a noble knight",
    "a mysterious bard",
    "a vengeful spirit",
    "a disgraced noble",
    "a forgotten god",
    "a curious scholar",
    "a resourceful ranger",
    "a ruthless warlord",
    "a benevolent healer",
    "a renegade pirate",
    "a haunted paladin",
    "a mystical druid",
    "a charming swindler",
    "a fierce barbarian",
    "enigmatic oracle",
    "a rebellious prince/princess",
    "a cursed blacksmith",
    "exiled monarch",
    "a zealous cleric",
    "a devious assassin",
    "a wandering nomad",
    "a corrupted priest",
    "a holy knight",
    "a reclusive alchemist",
    "a determined hunter",
    "a playful trickster",
    "a brave adventurer",
    "a sinister necromancer",
    "a devoted monk",
    "a lost child",
    "enchanted beast",
    "a fearless captain",
    "a time-traveling mage",
    "ancient dragon",
    "a skilled artisan",
    "a tragic hero",
    "a wisecracking thief",
    "a silent guardian",
    "a cursed noble",
    "a daring explorer",
    "a forgotten hero",
    "a blind prophet",
    "a brave soldier",
    "a calculating tactician",
    "a wandering minstrel",
    "a fallen angel",
    "a stoic blacksmith",
    "a feral werewolf",
    "a gentle giant",
    "a paranoid scholar",
    "a jovial innkeeper",
    "a mischievous fae",
    "a ghostly apparition",
    "a heroic outlaw",
    "a loyal retainer",
    "a ruthless bounty hunter",
    "a patient gardener",
    "a wise hermit",
    "a cunning shapeshifter",
    "a vigilant watchman",
    "a conflicted spy",
    "a ghostly knight",
    "a shrewd politician",
    "a vengeful widow",
    "a daring smuggler",
    "a noble philanthropist",
    "a cursed artist",
    "a reformed villain",
    "a brave sailor",
    "eccentric inventor",
    "a lost explorer",
    "a fierce gladiator",
    "a pacifist healer",
    "a corrupt judge",
    "a jovial bard",
    "a hardened mercenary",
    "a benevolent spirit",
    "a secretive librarian",
    "a wild druid",
    "a tortured artist",
    "a brave diplomat",
    "a fallen hero",
    "a loyal squire",
    "a shadowy figure",
    "a mysterious benefactor",
    "a determined farmer",
    "a noble defender",
    "a curious child",
    "a wise elder",
    "a fearless leader",
    "a jovial merchant",
    "a shamanistic healer",
    "a royal guard"
];

export const goals = [
    "retrieve a lost artifact",
    "rescue a captured ally",
    "uncover an ancient secret",
    "defend a village from raiders",
    "escort a caravan safely",
    "assassinate a tyrant",
    "solve a series of murders",
    "steal a powerful relic",
    "sent to negotiate peace between factions",
    "find a cure for a deadly disease",
    "sabotage an enemy stronghold",
    "charged to protect a sacred site",
    "explore a haunted mansion",
    "recover stolen plans",
    "ordered to infiltrate a cult",
    "escort a VIP through dangerous territory",
    "defend a fort under siege",
    "find a missing scout",
    "capture a notorious bandit",
    "decipher an ancient prophecy",
    "assigned to build an outpost",
    "gather intel on enemy movements",
    "retrieve a magical ingredient",
    "estigate strange occurrences",
    "escort a diplomat to a summit",
    "defeat a rampaging beast",
    "clear a dungeon",
    "rescue prisoners of war",
    "retrieve a lost heirloom",
    "sent to stop a ritual",
    "find a way to stop a plague",
    "sabotage a magical portal",
    "charged to protect a royal family",
    "deliver a critical message",
    "rescue a kidnapped noble",
    "recover a legendary weapon",
    "iltrate an enemy camp",
    "protect a merchant caravan",
    "ordered to capture a rogue mage",
    "retrieve a forbidden tome",
    " gather rare herbs",
    "assigned to find a hidden treasure",
    "defend a border town",
    "stop a smuggling ring",
    "estigate a lost expedition",
    "escort refugees to safety",
    "find a hidden sanctuary",
    "guard a shipment of gold",
    "capture a runaway criminal",
    "sabotage a siege engine",
    "sent to investigate an abandoned mine",
    "protect a sacred relic",
    "uncover a spy network",
    "charged to defend a wizard’s tower",
    "find and close a demon portal",
    "deliver supplies to a besieged city",
    "find an ancient map",
    "rescue survivors from a disaster",
    "iltrate a masquerade ball",
    "track down a rare beast",
    "gather evidence of corruption",
    "free a wrongly accused prisoner",
    "sent to negotiate a ransom",
    "protect a valuable artifact",
    "escort a healer to a plague site",
    "recover a stolen spellbook",
    "stop an assassination plot",
    "estigate a cursed village",
    "ordered to explore an uncharted island",
    "defend a temple from invaders",
    "find a missing diplomat",
    "sabotage a mining operation",
    "protect a group of pilgrims",
    "retrieve a magical crystal",
    "charged to defeat a rival guild",
    "stop a warlord’s plans",
    "protect a library of ancient texts",
    "uncover a hidden conspiracy",
    "find the source of dark magic",
    "rescue a stranded expedition",
    "sent to destroy a dangerous artifact",
    "capture a rebel leader",
    "guard a sacred grove",
    "recover an ancient artifact",
    "defeat a powerful demon",
    "protect a trade route",
    "retrieve a lost manuscript",
    "estigate a series of disappearances",
    "sabotage a fleet of ships",
    "charged to rescue a besieged garrison",
    "escort a bard to a royal court",
    "find a cure for a magical illness",
    "protect a village from a curse",
    "stop a dangerous cult ritual",
    "rescue a child from kidnappers",
    "sent to uncover a hidden temple",
    "defend a fortress from attackers",
    "retrieve a stolen banner",
    "gather rare ingredients",
    "uncover the truth behind a legend",
    "protect a scholar on a quest",
    "find a mythical creature"
];

export const locations = [
    "abandoned castle",
    "bustling underground market",
    "mysterious forest",
    "haunted mansion",
    "desolate island",
    "ancient ruin",
    "sacred temple",
    "remote mountain village",
    "forgotten city",
    "magical grove",
    "stormy sea",
    "war-torn battlefield",
    "secret laboratory",
    "dragon’s lair",
    "sunken ship",
    "royal palace",
    "cursed swamp",
    "enchanted garden",
    "floating island",
    "shadowy forest",
    "maze-like cavern",
    "ghost town",
    "wizard's tower",
    "desolate desert",
    "icy tundra",
    "hidden valley",
    "labyrinthine dungeon",
    "mystical monastery",
    "celestial plane",
    "underground cavern",
    "forgotten fortress",
    "bustling port city",
    "high cliffside",
    "serene oasis",
    "lava-filled chasm",
    "plague-ridden town",
    "treacherous mountain path",
    "ancient library",
    "secret guild hall",
    "magical battlefield",
    "fog-shrouded moor",
    "haunted graveyard",
    "dark forest",
    "hidden underwater city",
    "sacred pilgrimage trail",
    "nomadic caravan camp",
    "feywild grove",
    "bustling metropolis",
    "mystical ley line",
    "clockwork city",
    "star-lit observatory",
    "elemental plane",
    "forgotten mine",
    "druidic circle",
    "bandit camp",
    "legendary battlefield",
    "subterranean labyrinth",
    "royal crypt",
    "verdant plateau",
    "sorcerer's sanctum",
    "seedy tavern",
    "wizard's college",
    "foggy coastline",
    "hunter’s lodge",
    "tranquil monastery",
    "desolate wasteland",
    "celestial island",
    "ancient coliseum",
    "pirate's cove",
    "moonlit grove",
    "cursed battlefield",
    "reclusive monastery",
    "ancient arena",
    "darkened alley",
    "holy pilgrimage site",
    "desolate ice cave",
    "thriving marketplace",
    "secluded hermitage",
    "distant star",
    "gnomish workshop",
    "haunted asylum",
    "mystical forge",
    "sun-scorched plateau",
    "serene village",
    "spectral realm",
    "cryptic maze",
    "sacred mountaintop",
    "ancient grove",
    "bustling bazaar",
    "forgotten realm",
    "dragon’s hoard",
    "haunted lighthouse",
    "hidden sanctuary",
    "demon-infested ruin",
    "tranquil lake",
    "mystical forest clearing",
    "bustling trade post",
    "windswept canyon",
    "ancient battlefield",
    "serene mountain retreat",
    "dragon’s nest",
    "hidden monastery",
    "celestial observatory",
    "otherworldly dimension"
];

export const obstacles = [
    "undead warriors",
    "deadly puzzles",
    "rival adventurers",
    "a powerful curse",
    "enchanted traps",
    "a magical barrier",
    "deadly creatures",
    "a maze of tunnels",
    "a vigilant guard",
    "ancient magic",
    "a fearsome dragon",
    "treacherous terrain",
    "booby-trapped with explosive runes",
    "a group of mercenaries",
    "shifting sands",
    "an army of golems",
    "a horde of minions",
    "a fierce warlord",
    "illusionary magic",
    "giant spiders",
    "a waterfall",
    "spectral knights",
    "a powerful sorcerer",
    "a labyrinthine dungeon",
    "elemental guardians",
    "a time loop",
    "a monstrous beast",
    "a dense forest",
    "a ring of fire",
    "a tribe of barbarians",
    "an elite squad",
    "a fallen bridge",
    "a mythical creature",
    "a magical storm",
    "a sinking ship",
    "a haunted spirit",
    "an icy cavern",
    "a shield of light",
    "a stone colossus",
    "an enchanted mirror",
    "a dark wizard",
    "a toxic swamp",
    "shadowy figures",
    "a volcano",
    "a barrier of thorns",
    "a powerful lich",
    "in a cursed painting",
    "a swarm of bats",
    "a raging river",
    "a clan of ninjas",
    "enchanted fog",
    "a forgotten temple",
    "a circle of stones",
    "a demonic entity",
    "a sinking bog",
    "a fire-breathing dragon",
    "a cursed knight",
    "a field of illusions",
    "a forcefield",
    "a band of pirates",
    "enchanted vines",  
    "a rockslide",
    "a pack of wolves",
    "a shifting maze",
    "a wall of ice",
    "a vengeful spirit",
    "a mountain pass",
    "a magical fog",
    "a thunderous beast",
    "a collapsing cave",
    "a clan of warriors",
    "a cursed relic",
    "a forest of shadows",
    "a blizzard",
    "a swamp monster",
    "an abandoned mine",
    "a sentient tree",
    "a sandstorm",
    "a sunken ruin",
    "a basilisk",
    "a spell of confusion",
    "a haunted crypt",
    "a werewolf pack",
    "a landslide",
    "an ancient seal",
    "an iron golem",
    "a snowy tundra",
    "a moat of lava",
    "a magical mist",
    "a cursed artifact",
    "a phantom ship",
    "a frost giant",
    "a lightning storm",
    "a ring of ice",
    "a desert oasis",
    "enchanted flames",
    "a feral beast",
    "a deadly game",
    "an ethereal guardian"
];

export const twists = [
    "allies turn into enemies",
    "a powerful storm disrupts plans",
    "a long-lost mentor reappears",
    "a traitor in the group",
    "magic stops working",
    "time flows differently",
    "a hidden agenda is revealed",
    "a rival claims the prize",
    "everything is an illusion",
    "a mysterious benefactor aids the party",
    "a sudden betrayal",
    "the enemy seeks redemption",
    "a curse affects everyone",
    "a hidden passage is found",
    "a forgotten ally returning",
    "memories are altered",
    "reality is distorted",
    "a natural disaster strikes",
    "ancient prophecy fulfilled",
    "technology fails",
    "dreams become reality",
    "a secret society intervenes",
    "a race against time",
    "the dead rise again",
    "shadows come to life",
    "a powerful artifact awakens",
    "a sudden invasion",
    "the weather turns deadly",
    "illusions conceal truths",
    "ally is possessed",
    "a double-cross is revealed",
    "all seems lost",
    "visions predict doom",
    "a mysterious illness spreads",
    "trust is broken",
    "the ground shifts",
    "a powerful entity awakens",
    "unexpected reinforcements",
    "the past haunts the present",
    "secrets are uncovered",
    "a dire prophecy revealed",
    "old enemy returns",
    "a hidden portal is found",
    "a powerful curse lifted",
    "a key item is lost",
    "a deadly trap is sprung",
    "allies are mind-controlled",
    "a race against an eclipse",
    "the truth is stranger",
    "a hidden enemy lurks",
    "a sudden change of heart",
    "the leader is captured",
    "ient technology revives",
    "unexpected alliance begins",
    "reality fractures",
    "a powerful spell backfires",
    "nature goes berserk",
    "enemy seeks peace",
    "everyone forgets",
    "a doppelganger is found",
    "time loops endlessly",
    "a sudden moral dilemma",
    "a secret is unveiled",
    "a forbidden area opens",
    "a desperate gamble",
    "the heroes are framed",
    "the sun never sets",
    "a powerful weapon is used",
    "unexpected death",
    "ally is a spy",
    "ancient evil awakens",
    "all magic is drained",
    "a lost civilization discovered",
    "the moon shatters",
    "the sea becomes hostile",
    "gravity shifts",
    "a sudden epidemic",
    "the heroes turn against each other",
    "the stars align",
    "day and night swap",
    "a hidden map is found",
    "the ground opens",
    "dreams invade reality",
    "a deal is struck",
    "artifact causes chaos",
    "a prophecy is false",
    "unexpected hero rises",
    "emotions are manipulated",
    "a secret is revealed",
    "heroes are cursed",
    "alternate dimension overlaps",
    "the sky darkens",
    "a powerful entity is bound",
    "a hero disappears",
    "a shadows speak",
    "silence falls",
    "unbreakable oath",
    "the heroes face their fears"
];
