export const characters = [
    "a treacherous merchant",
    "a loyal sidekick",
    "a cunning sorcerer",
    "a fierce warrior",
    "a stealthy rogue",
    "a noble knight",
    "a mysterious bard",
    "a vengeful spirit",
    "a disgraced noble",
    "a forgotten god",
    "a curious scholar",
    "a resourceful ranger",
    "a ruthless warlord",
    "a benevolent healer",
    "a renegade pirate",
    "a haunted paladin",
    "a mystical druid",
    "a charming swindler",
    "a fierce barbarian",
    "an enigmatic oracle",
    "a rebellious prince/princess",
    "a cursed blacksmith",
    "an exiled monarch",
    "a zealous cleric",
    "a devious assassin",
    "a wandering nomad",
    "a corrupted priest",
    "a holy knight",
    "a reclusive alchemist",
    "a determined hunter",
    "a playful trickster",
    "a brave adventurer",
    "a sinister necromancer",
    "a devoted monk",
    "a lost child",
    "an enchanted beast",
    "a fearless captain",
    "a time-traveling mage",
    "an ancient dragon",
    "a skilled artisan",
    "a tragic hero",
    "a wisecracking thief",
    "a silent guardian",
    "a cursed noble",
    "a daring explorer",
    "a forgotten hero",
    "a blind prophet",
    "a brave soldier",
    "a calculating tactician",
    "a wandering minstrel",
    "a fallen angel",
    "a stoic blacksmith",
    "a feral werewolf",
    "a gentle giant",
    "a paranoid scholar",
    "a jovial innkeeper",
    "a mischievous fae",
    "a ghostly apparition",
    "a heroic outlaw",
    "a loyal retainer",
    "a ruthless bounty hunter",
    "a patient gardener",
    "a wise hermit",
    "a cunning shapeshifter",
    "a vigilant watchman",
    "a conflicted spy",
    "a ghostly knight",
    "a shrewd politician",
    "a vengeful widow",
    "a daring smuggler",
    "a noble philanthropist",
    "a cursed artist",
    "a reformed villain",
    "a brave sailor",
    "an eccentric inventor",
    "a lost explorer",
    "a fierce gladiator",
    "a pacifist healer",
    "a corrupt judge",
    "a jovial bard",
    "a hardened mercenary",
    "a benevolent spirit",
    "a secretive librarian",
    "a wild druid",
    "a tortured artist",
    "a brave diplomat",
    "a fallen hero",
    "a loyal squire",
    "a shadowy figure",
    "a mysterious benefactor",
    "a determined farmer",
    "a noble defender",
    "a curious child",
    "a wise elder",
    "a fearless leader",
    "a jovial merchant",
    "a shamanistic healer",
    "a royal guard"
];

export const goals = [
   "must retrieve a lost artifact",
    "need to rescue a captured ally",
    "are tasked to uncover an ancient secret",
    "must defend a village from raiders",
    "need to escort a caravan safely",
    "are hired to assassinate a tyrant",
    "must solve a series of murders",
    "need to steal a powerful relic",
    "are sent to negotiate peace between factions",
    "must find a cure for a deadly disease",
    "need to sabotage an enemy stronghold",
    "are charged to protect a sacred site",
    "must explore a haunted mansion",
    "need to recover stolen plans",
    "are ordered to infiltrate a cult",
    "must escort a VIP through dangerous territory",
    "need to defend a fort under siege",
    "are tasked to find a missing scout",
    "must capture a notorious bandit",
    "need to decipher an ancient prophecy",
    "are assigned to build an outpost",
    "must gather intel on enemy movements",
    "need to retrieve a magical ingredient",
    "are tasked to investigate strange occurrences",
    "must escort a diplomat to a summit",
    "need to defeat a rampaging beast",
    "are hired to clear a dungeon",
    "must rescue prisoners of war",
    "need to retrieve a lost heirloom",
    "are sent to stop a ritual",
    "must find a way to stop a plague",
    "need to sabotage a magical portal",
    "are charged to protect a royal family",
    "must deliver a critical message",
    "need to rescue a kidnapped noble",
    "are tasked to recover a legendary weapon",
    "must infiltrate an enemy camp",
    "need to protect a merchant caravan",
    "are ordered to capture a rogue mage",
    "must retrieve a forbidden tome",
    "need to gather rare herbs",
    "are assigned to find a hidden treasure",
    "must defend a border town",
    "need to stop a smuggling ring",
    "are tasked to investigate a lost expedition",
    "must escort refugees to safety",
    "need to find a hidden sanctuary",
    "are hired to guard a shipment of gold",
    "must capture a runaway criminal",
    "need to sabotage a siege engine",
    "are sent to investigate an abandoned mine",
    "must protect a sacred relic",
    "need to uncover a spy network",
    "are charged to defend a wizard’s tower",
    "must find and close a demon portal",
    "need to deliver supplies to a besieged city",
    "are tasked to find an ancient map",
    "must rescue survivors from a disaster",
    "need to infiltrate a masquerade ball",
    "are hired to track down a rare beast",
    "must gather evidence of corruption",
    "need to free a wrongly accused prisoner",
    "are sent to negotiate a ransom",
    "must protect a valuable artifact",
    "need to escort a healer to a plague site",
    "are tasked to recover a stolen spellbook",
    "must stop an assassination plot",
    "need to investigate a cursed village",
    "are ordered to explore an uncharted island",
    "must defend a temple from invaders",
    "need to find a missing diplomat",
    "are hired to sabotage a mining operation",
    "must protect a group of pilgrims",
    "need to retrieve a magical crystal",
    "are charged to defeat a rival guild",
    "must stop a warlord’s plans",
    "need to protect a library of ancient texts",
    "are tasked to uncover a hidden conspiracy",
    "must find the source of dark magic",
    "need to rescue a stranded expedition",
    "are sent to destroy a dangerous artifact",
    "must capture a rebel leader",
    "need to guard a sacred grove",
    "are assigned to recover an ancient artifact",
    "must defeat a powerful demon",
    "need to protect a trade route",
    "are hired to retrieve a lost manuscript",
    "must investigate a series of disappearances",
    "need to sabotage a fleet of ships",
    "are charged to rescue a besieged garrison",
    "must escort a bard to a royal court",
    "need to find a cure for a magical illness",
    "are tasked to protect a village from a curse",
    "must stop a dangerous cult ritual",
    "need to rescue a child from kidnappers",
    "are sent to uncover a hidden temple",
    "must defend a fortress from attackers",
    "need to retrieve a stolen banner",
    "are hired to gather rare ingredients",
    "must uncover the truth behind a legend",
    "need to protect a scholar on a quest",
    "are tasked to find a mythical creature"
];

export const locations = [
    "in an abandoned castle",
    "within a bustling underground market",
    "deep in a mysterious forest",
    "in a haunted mansion",
    "on a desolate island",
    "in an ancient ruin",
    "within a sacred temple",
    "in a remote mountain village",
    "underneath a forgotten city",
    "in a magical grove",
    "on a stormy sea",
    "in a war-torn battlefield",
    "within a secret laboratory",
    "in a dragon’s lair",
    "in a sunken ship",
    "within a royal palace",
    "in a cursed swamp",
    "in an enchanted garden",
    "on a floating island",
    "in a shadowy forest",
    "within a maze-like cavern",
    "in a ghost town",
    "within a wizard's tower",
    "in a desolate desert",
    "on an icy tundra",
    "in a hidden valley",
    "within a labyrinthine dungeon",
    "in a mystical monastery",
    "on a celestial plane",
    "in an underground cavern",
    "within a forgotten fortress",
    "in a bustling port city",
    "on a high cliffside",
    "within a serene oasis",
    "in a lava-filled chasm",
    "in a plague-ridden town",
    "on a treacherous mountain path",
    "within an ancient library",
    "in a secret guild hall",
    "on a magical battlefield",
    "in a fog-shrouded moor",
    "in a haunted graveyard",
    "within a dark forest",
    "in a hidden underwater city",
    "on a sacred pilgrimage trail",
    "in a nomadic caravan camp",
    "within a feywild grove",
    "in a bustling metropolis",
    "on a mystical ley line",
    "within a clockwork city",
    "in a star-lit observatory",
    "on an elemental plane",
    "in a forgotten mine",
    "within a druidic circle",
    "in a bandit camp",
    "on a legendary battlefield",
    "in a subterranean labyrinth",
    "within a royal crypt",
    "on a verdant plateau",
    "in a sorcerer's sanctum",
    "within a seedy tavern",
    "in a wizard's college",
    "on a foggy coastline",
    "in a hunter’s lodge",
    "within a tranquil monastery",
    "in a desolate wasteland",
    "on a celestial island",
    "in an ancient coliseum",
    "within a pirate's cove",
    "in a moonlit grove",
    "on a cursed battlefield",
    "in a reclusive monastery",
    "within an ancient arena",
    "in a darkened alley",
    "on a holy pilgrimage site",
    "in a desolate ice cave",
    "within a thriving marketplace",
    "in a secluded hermitage",
    "on a distant star",
    "in a gnomish workshop",
    "within a haunted asylum",
    "in a mystical forge",
    "on a sun-scorched plateau",
    "in a serene village",
    "within a spectral realm",
    "in a cryptic maze",
    "on a sacred mountaintop",
    "in an ancient grove",
    "within a bustling bazaar",
    "in a forgotten realm",
    "on a dragon’s hoard",
    "in a haunted lighthouse",
    "within a hidden sanctuary",
    "in a demon-infested ruin",
    "on a tranquil lake",
    "in a mystical forest clearing",
    "within a bustling trade post",
    "in a windswept canyon",
    "on an ancient battlefield",
    "in a serene mountain retreat",
    "within a dragon’s nest",
    "in a hidden monastery",
    "on a celestial observatory",
    "in an otherworldly dimension"
];

export const obstacles = [
     "guarded by undead warriors",
    "trapped with deadly puzzles",
    "hunted by rival adventurers",
    "protected by a powerful curse",
    "defended by enchanted traps",
    "blocked by a magical barrier",
    "infested with deadly creatures",
    "hidden in a maze of tunnels",
    "patrolled by a vigilant guard",
    "sealed by ancient magic",
    "guarded by a fearsome dragon",
    "surrounded by treacherous terrain",
    "booby-trapped with explosive runes",
    "guarded by a group of mercenaries",
    "hidden within shifting sands",
    "defended by an army of golems",
    "protected by a horde of minions",
    "guarded by a fierce warlord",
    "obscured by illusionary magic",
    "infested with giant spiders",
    "hidden behind a waterfall",
    "guarded by spectral knights",
    "defended by a powerful sorcerer",
    "hidden in a labyrinthine dungeon",
    "protected by elemental guardians",
    "trapped in a time loop",
    "guarded by a monstrous beast",
    "hidden within a dense forest",
    "protected by a ring of fire",
    "guarded by a tribe of barbarians",
    "defended by an elite squad",
    "blocked by a fallen bridge",
    "guarded by a mythical creature",
    "surrounded by a magical storm",
    "trapped in a sinking ship",
    "guarded by a haunted spirit",
    "hidden in an icy cavern",
    "protected by a shield of light",
    "guarded by a stone colossus",
    "trapped in an enchanted mirror",
    "defended by a dark wizard",
    "surrounded by a toxic swamp",
    "guarded by shadowy figures",
    "hidden within a volcano",
    "protected by a barrier of thorns",
    "guarded by a powerful lich",
    "trapped in a cursed painting",
    "defended by a swarm of bats",
    "blocked by a raging river",
    "guarded by a clan of ninjas",
    "surrounded by enchanted fog",
    "hidden in a forgotten temple",
    "protected by a circle of stones",
    "guarded by a demonic entity",
    "trapped in a sinking bog",
    "defended by a fire-breathing dragon",
    "guarded by a cursed knight",
    "hidden in a field of illusions",
    "protected by a forcefield",
    "guarded by a band of pirates",
    "surrounded by enchanted vines",
    "blocked by a rockslide",
    "guarded by a pack of wolves",
    "trapped in a shifting maze",
    "protected by a wall of ice",
    "guarded by a vengeful spirit",
    "hidden within a mountain pass",
    "protected by a magical fog",
    "guarded by a thunderous beast",
    "trapped in a collapsing cave",
    "defended by a clan of warriors",
    "guarded by a cursed relic",
    "hidden in a forest of shadows",
    "protected by a blizzard",
    "guarded by a swamp monster",
    "trapped in an abandoned mine",
    "defended by a sentient tree",
    "surrounded by a sandstorm",
    "hidden in a sunken ruin",
    "guarded by a basilisk",
    "protected by a spell of confusion",
    "trapped in a haunted crypt",
    "guarded by a werewolf pack",
    "blocked by a landslide",
    "protected by an ancient seal",
    "guarded by an iron golem",
    "hidden in a snowy tundra",
    "surrounded by a moat of lava",
    "protected by a magical mist",
    "guarded by a cursed artifact",
    "trapped in a phantom ship",
    "defended by a frost giant",
    "guarded by a lightning storm",
    "protected by a ring of ice",
    "hidden in a desert oasis",
    "surrounded by enchanted flames",
    "guarded by a feral beast",
    "trapped in a deadly game",
    "defended by an ethereal guardian"
];

export const twists = [
   "allies turn into enemies",
    "a powerful storm disrupts plans",
    "a long-lost mentor reappears",
    "a traitor in the group",
    "magic stops working",
    "time flows differently",
    "a hidden agenda is revealed",
    "a rival claims the prize",
    "everything is an illusion",
    "a mysterious benefactor aids the party",
    "a sudden betrayal",
    "the enemy seeks redemption",
    "a curse affects everyone",
    "a hidden passage is found",
    "a forgotten ally returning",
    "memories are altered",
    "reality is distorted",
    "a natural disaster strikes",
    "an ancient prophecy fulfilled",
    "technology fails",
    "dreams become reality",
    "a secret society intervenes",
    "a race against time",
    "the dead rise again",
    "shadows come to life",
    "a powerful artifact awakens",
    "a sudden invasion",
    "the weather turns deadly",
    "illusions conceal truths",
    "an ally is possessed",
    "a double-cross is revealed",
    "all seems lost",
    "visions predict doom",
    "a mysterious illness spreads",
    "trust is broken",
    "the ground shifts",
    "a powerful entity awakens",
    "unexpected reinforcements",
    "the past haunts the present",
    "secrets are uncovered",
    "a dire prophecy revealed",
    "an old enemy returns",
    "a hidden portal is found",
    "a powerful curse lifted",
    "a key item is lost",
    "a deadly trap is sprung",
    "allies are mind-controlled",
    "a race against an eclipse",
    "the truth is stranger",
    "a hidden enemy lurks",
    "a sudden change of heart",
    "the leader is captured",
    "ancient technology revives",
    "an unexpected alliance begins",
    "reality fractures",
    "a powerful spell backfires",
    "nature goes berserk",
    "an enemy seeks peace",
    "everyone forgets",
    "a doppelganger is found",
    "time loops endlessly",
    "a sudden moral dilemma",
    "a secret is unveiled",
    "a forbidden area opens",
    "a desperate gamble",
    "the heroes are framed",
    "the sun never sets",
    "a powerful weapon is used",
    "an unexpected death",
    "an ally is a spy",
    "an ancient evil awakens",
    "all magic is drained",
    "a lost civilization discovered",
    "the moon shatters",
    "the sea becomes hostile",
    "gravity shifts",
    "a sudden epidemic",
    "the heroes turn against each other",
    "the stars align",
    "day and night swap",
    "a hidden map is found",
    "the ground opens",
    "dreams invade reality",
    "a deal is struck",
    "an artifact causes chaos",
    "a prophecy is false",
    "an unexpected hero rises",
    "emotions are manipulated",
    "a secret is revealed",
    "heroes are cursed",
    "an alternate dimension overlaps",
    "the sky darkens",
    "a powerful entity is bound",
    "a hero disappears",
    "a shadows speak",
    "silence falls",
    "an unbreakable oath",
    "the heroes face their fears"
];
